FROM ubuntu:20.04

RUN sed -i 's@archive.ubuntu.com@ftp.jaist.ac.jp/pub/Linux@g' /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y python3 python3-pip

RUN pip3 install jupyterlab

RUN pip3 install Flask
ENV FLASK_APP hello.py

WORKDIR /var/volume/cashman-flask-project

CMD flask run --host 0.0.0.0 --port 5000

