FROM ubuntu:20.04

RUN sed -i 's@archive.ubuntu.com@ftp.jaist.ac.jp/pub/Linux@g' /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y python3 python3-pip

RUN pip3 install jupyterlab

RUN pip3 install Flask
RUN pip3 install marshmallow

WORKDIR /var/volume

ENTRYPOINT ["/var/volume/cashman-flask-project/bootstrap.sh"]

