version: '3'

services:
        container_01:
                build:
                        context: .
                        dockerfile: Dockerfile
                ports:
                 - "8888:8888"
